// Section 5–16 of "CAT 2026 Quant Guide: Arithmetic + Easy Algebra (55-Day Targeted Plan)",
// transcribed as data. Every worked example and practice question is original to the guide
// (built to mirror recurring CAT patterns), not a reproduced past-paper question.

export type Example = { tag?: string; q: string; a: string };
export type ConceptGroup = { title?: string; items: string[]; tex?: string[] };

export type Chapter = {
  n: number;
  slug: string;
  title: string;
  short: string;
  group: "Arithmetic" | "Algebra";
  lede: string;
  asked: string;
  concepts: ConceptGroup[];
  thought: string[];
  patterns: string[];
  evidence?: string;
  examples: Example[];
  traps: string[];
  practice: { q: string; a: string }[];
};

export const chapters: Chapter[] = [
  {
    n: 5,
    slug: "percentages",
    title: "Percentages",
    short: "Percentages",
    group: "Arithmetic",
    lede: "Percentages rarely appear as a standalone CAT question now, but they sit inside profit-loss, interest, mixtures and most word problems. Master the fraction method here and every later chapter gets faster.",
    asked:
      "Recent papers wrap percentages in a story: spending and saving, elections, exam marks, price and consumption, population change. The maths is light; the trap is always the base, “percent of what?”.",
    concepts: [
      {
        items: [
          "x% of y = y% of x. Example: 8% of 50 = 50% of 8 = 4.",
          "Percentage change = (new − old) ÷ old × 100.",
          "If A is r% more than B, then B is r ÷ (100 + r) × 100% less than A. If A is r% less than B, then B is r ÷ (100 − r) × 100% more than A.",
          "Product rule: if price × quantity stays fixed and price rises by a fraction 1/n, quantity must fall by 1/(n + 1).",
          "Percentage points vs percent: a rate moving from 10% to 12% rose by 2 percentage points, which is a 20% increase.",
          "Growth over n periods: P × (1 + r/100)ⁿ. Decline: P × (1 − r/100)ⁿ.",
          "Two successive changes of a% and b% (use negative values for decreases):",
        ],
        tex: [String.raw`\text{Net change \%} = a + b + \frac{a \times b}{100}`],
      },
    ],
    thought: [
      "Pick a base: assume the starting value is 100, or an LCM of the denominators.",
      "Convert each percentage into a fraction or multiplying factor.",
      "Ask “percent of what?” for every number. When the base changes (“% of the remainder”), update it.",
      "Chain the factors, then convert back to the quantity asked.",
    ],
    patterns: [
      "Successive changes: price up then down, salary hikes and cuts, population over years. Multiply the factors.",
      "Chained comparisons: “A is 20% more than B, which is 25% less than C”. Set C = 100 and walk down the chain.",
      "Product constancy: expenditure = price × quantity, revenue = price × units, area = length × breadth. Fix the product, change one factor, find the other.",
      "Spending from the remainder: x% on rent, then y% of the rest on food. Multiply the “remaining” fractions.",
      "Elections: registered voters → votes cast → valid votes → winner’s share and margin. Each stage has its own base.",
      "Pass marks: “scored 178 and failed by 22” means the pass mark is 200.",
      "Mixed groups: different shares of boys and girls pass; the overall share is a weighted average (Section 10).",
      "Overlapping groups: passed A, passed B, passed both. Total = A + B − both + neither.",
    ],
    examples: [
      { tag: "successive changes", q: "A phone’s price is raised 25%, cut 20% in a sale, then raised 10%. What is the net change from the original price?", a: "Factors 5/4 × 4/5 × 11/10 = 11/10. Answer: +10%." },
      { tag: "product constancy", q: "Petrol prices rise 25%. By what percent must a family cut consumption to keep its spending unchanged?", a: "Price × 5/4, so quantity × 4/5, a fall of 1/5. Answer: 20%." },
      { tag: "base flip", q: "Ravi earns 25% more than Anil. By what percent is Anil’s salary less than Ravi’s?", a: "Anil = 100, Ravi = 125. The gap of 25 out of 125 is 1/5. Answer: 20%." },
      { tag: "spending from the remainder", q: "Meera spends 30% of her income on rent, 25% of the remainder on food and 20% of what is then left on travel. She saves ₹16,800. Find her income.", a: "Share left after each step: 0.7 × 0.75 × 0.8 = 0.42 of income. 0.42 × income = 16,800. Answer: ₹40,000." },
      { tag: "elections", q: "In a two-candidate election, 80% of registered voters voted and 5% of the votes cast were invalid. The winner got 55% of valid votes and won by 1,520 votes. How many voters were registered?", a: "Valid votes = 0.95 × 0.8 × V = 0.76V. Margin = (55 − 45)% of valid votes = 0.076V = 1,520. Answer: 20,000." },
      { tag: "pass marks", q: "Passing needs 40% of the maximum marks. Arjun scored 178 and failed by 22 marks. What are the maximum marks?", a: "Pass mark = 178 + 22 = 200 = 40% of the maximum. Answer: 500." },
      { tag: "mixed groups", q: "60% of a school’s students are boys. 20% of the boys and 35% of the girls joined the NCC. What percent of students did not join?", a: "Take 100 students. Joined: 12 boys + 14 girls = 26. Answer: 74%." },
      { tag: "population chain", q: "A town grows 10%, shrinks 10%, then grows 20% over three years, ending at 23,760. What was the initial population?", a: "Net factor 1.1 × 0.9 × 1.2 = 1.188. 23,760 ÷ 1.188 = 20,000. Answer: 20,000." },
    ],
    traps: [
      "Averaging percentages from groups of different sizes; weight them by size instead.",
      "Treating “+20% then −20%” as no change. It is −4%.",
      "Confusing percentage points with percent.",
      "Forgetting that “% of the remainder” uses a new base.",
    ],
    practice: [
      { q: "A number is increased by 20% and then decreased by 20%. What is the net percentage change?", a: "−4%: 20 − 20 − 400/100." },
      { q: "A 20% fall in the price of sugar lets a person buy 2 kg more for ₹400. Find the original price per kg.", a: "₹50: the 20% saving is ₹80, which buys 2 kg at the new ₹40/kg; the original was 40 ÷ 0.8." },
      { q: "A’s income is 20% less than B’s. By what percent is B’s income more than A’s?", a: "25%: 20/80." },
      { q: "A rectangle’s length rises 20% and its breadth falls 10%. What is the change in area?", a: "+8%: 1.2 × 0.9 = 1.08." },
      { q: "65% of students passed English, 55% passed Maths and 30% passed both. What percent failed both?", a: "10%: passed at least one = 65 + 55 − 30 = 90." },
      { q: "A shop’s unit sales fall 10% while the price per unit rises 15%. What is the change in revenue?", a: "+3.5%: 0.9 × 1.15 = 1.035." },
      { q: "In a two-candidate contest with no invalid votes, the loser got 35% and lost by 15,000 votes. How many votes were cast?", a: "50,000: the 30% margin is 15,000." },
      { q: "Rahul spends 40% of his income on the household and 20% of the rest on rent, and saves ₹14,400. What is his income?", a: "₹30,000: 0.6 × 0.8 = 0.48 of income = 14,400." },
    ],
  },
  {
    n: 6,
    slug: "profit-loss-discount",
    title: "Profit, Loss & Discount",
    short: "Profit & Loss",
    group: "Arithmetic",
    lede: "Profit-loss is one of CAT’s most reliable sources: most years carry a markup-discount chain, a two-scenario question or a buy-and-sell chain. All three reduce to multiplying factors on an assumed cost price of 100.",
    asked:
      "A shop marks up and discounts; a trader sells at a loss and would have gained by selling for more; goods pass from A to B to C and sometimes back. Offers (“buy 3 get 1 free”), a dishonest dealer’s light weights and part-stocks sold at different margins also recur. Recent papers add cost structures (fixed + per-unit) and price–demand trade-offs.",
    concepts: [
      {
        items: [
          "Profit = SP − CP. Profit% is on CP unless stated: (SP − CP) ÷ CP × 100.",
          "Discount = MP − SP. Discount% is on MP (marked price).",
          "SP = CP × (1 + profit%/100) = MP × (1 − discount%/100).",
          "Markup m% then discount d% gives profit% = m − d − md/100.",
          "Successive discounts d₁ and d₂ equal one discount of d₁ + d₂ − d₁d₂/100.",
          "“Buy x, get y free” is a discount of y ÷ (x + y) on the goods taken.",
          "Dishonest dealer charging for the true weight but giving less: profit% = (true − given) ÷ given × 100.",
          "Two items sold at the same SP, one at x% profit and one at x% loss, always give an overall loss of x²/100 percent.",
          "A profit of p% on SP equals p ÷ (100 − p) × 100% on CP.",
          "The relation that links markup, discount and profit:",
        ],
        tex: [String.raw`\frac{MP}{CP} = \frac{100 + \text{profit \%}}{100 - \text{discount \%}}`],
      },
    ],
    thought: [
      "Assume CP = 100 unless real numbers are given.",
      "Write the chain CP → MP → SP with a factor on each arrow.",
      "In two-scenario questions, subtract: the gap between the two selling prices equals the gap between the two profit percentages, applied to CP.",
      "In chains of people, track one person’s cash: money in minus money out.",
    ],
    patterns: [
      "Markup + discount: find the profit, or the markup needed for a target profit (the MP/CP formula).",
      "Two scenarios: “8% loss at one price; 10% profit at ₹360 more” means 18% of CP = 360.",
      "Chains and buy-backs: A sells to B, B to C, or B sells back to A. Multiply factors, or track cash.",
      "Offer arithmetic: successive discounts, “buy n get m free”, a discount plus extra quantity.",
      "Dishonest dealer: false weights, sometimes combined with a markup or a discount.",
      "Partial sales: part of the stock at a profit and the rest at a loss. Use a weighted average or alligation.",
      "Same SP, opposite margins: always a net loss of x²/100 percent.",
      "Costs and demand: fixed + variable cost and break-even; price cuts that raise sales, then maximise revenue or profit (a quadratic, Section 13).",
    ],
    examples: [
      { tag: "markup + discount", q: "A shopkeeper marks goods 40% above cost and gives a 15% discount. What is his profit percent?", a: "1.40 × 0.85 = 1.19. Answer: 19%." },
      { tag: "required markup", q: "A trader wants a 20% profit after giving a 20% discount. How far above cost should he mark his goods?", a: "MP/CP = 120/80 = 1.5. Answer: 50% above cost." },
      { tag: "two scenarios", q: "A seller loses 8% at a certain price. Had he sold for ₹360 more, he would have gained 10%. Find the cost price.", a: "Moving from −8% to +10% is 18% of CP = 360. Answer: ₹2,000." },
      { tag: "buy-back chain", q: "Asha buys a bicycle for ₹5,000 and sells it to Bina at a 20% profit. Bina sells it back to Asha at a 10% loss, and Asha then sells it to Charu for ₹6,000. Find Asha’s total gain and her profit percent on the final sale.", a: "Bina’s buy-back price is 6,000 × 0.9 = 5,400. Asha’s cash: −5,000 + 6,000 − 5,400 + 6,000 = +1,600. The final sale earned 600 on 5,400. Answer: ₹1,600 in total; 11.11% on the final sale." },
      { tag: "offer + profit", q: "Shirts have a marked price of ₹1,000. The store offers “buy 4, get 1 free” plus 10% off the bill, and still makes a 20% profit. Find the cost price of one shirt.", a: "5 shirts cost the customer 4 × 1,000 × 0.9 = 3,600, so SP per shirt = 720. CP = 720 ÷ 1.2. Answer: ₹600." },
      { tag: "dishonest dealer", q: "A grocer gives 900 g for every 1 kg he charges for, and also prices his goods 10% above cost. What is his profit percent?", a: "Factor = 1.1 × 1000/900 = 1.2222. Answer: 22.22%. Without the markup it would be 100/900 = 11.11%." },
      { tag: "partial sale", q: "A trader sells one-third of his stock at a 20% profit and the rest at a 5% loss. What is the overall result?", a: "(1/3)(20) + (2/3)(−5) = 6.67 − 3.33. Answer: 3.33% profit." },
      { tag: "same SP", q: "Two phones sell at ₹9,900 each, one at a 10% profit and the other at a 10% loss. What is the overall result?", a: "Loss = 10²/100 = 1%. Check: the CPs are 9,000 and 11,000 (total 20,000) against SPs totalling 19,800. Answer: 1% loss (₹200)." },
      { tag: "price–demand", q: "A café sells 200 cups a day at ₹50, and every ₹1 cut in price adds 10 cups a day. Which price maximises revenue?", a: "With a cut of x rupees, revenue = (50 − x)(200 + 10x) = 10(50 − x)(20 + x). The two brackets always add to 70, so their product peaks when they are equal: 50 − x = 20 + x, giving x = 15. Answer: ₹35 (350 cups, revenue ₹12,250)." },
    ],
    traps: [
      "Taking profit% on SP, or discount% on CP.",
      "Adding successive discounts: 20% then 10% is 28%, not 30%.",
      "Double-counting in buy-back chains; track one person’s cash instead.",
      "“Buy 3 get 1 free” is 25% off, not 33.33%.",
    ],
    practice: [
      { q: "MP is 25% above CP and the discount is 12%. What is the profit percent?", a: "10%: 1.25 × 0.88 = 1.10." },
      { q: "A trader makes 25% profit after a 10% discount. What would his profit be at a 20% discount?", a: "11.11%: MP/CP = 125/90, and 125/90 × 0.8 = 100/90." },
      { q: "Selling at ₹720 gives a 10% loss. At what price should it be sold for a 25% profit?", a: "₹1,000: CP = 800." },
      { q: "What single discount equals successive discounts of 20% and 10%?", a: "28%." },
      { q: "What is the effective discount in “buy 3, get 2 free”?", a: "40%: 2/5." },
      { q: "A dealer sells at a 10% loss but gives 800 g for every 1 kg. What is his profit or loss percent?", a: "12.5% profit: 0.9 × 1000/800 = 1.125." },
      { q: "A man buys 12 pens for ₹10 and sells 10 pens for ₹12. What is his profit percent?", a: "44%: CP ₹0.833 and SP ₹1.20 per pen, and 1.2 ÷ 0.833 = 1.44." },
      { q: "Two items with the same CP are sold at a 25% profit and a 15% loss. What is the overall result?", a: "5% profit: (25 − 15)/2." },
      { q: "A workshop has fixed costs of ₹20,000 a month plus ₹30 per unit, and sells at ₹50 per unit. How many units must it sell to break even?", a: "1,000 units: each unit contributes ₹20 towards ₹20,000." },
    ],
  },
  {
    n: 7,
    slug: "simple-compound-interest",
    title: "Simple & Compound Interest",
    short: "SI & CI",
    group: "Arithmetic",
    lede: "SI/CI turns up less often than profit-loss or speed questions, but it is quick marks: most questions are one formula plus careful multiplying factors. Learn the five patterns below and the chapter is done in two sittings.",
    asked:
      "Money split across two or three rates; the gap between CI and SI; two investors compared under different schemes; loans repaid in equal instalments; amounts after successive years.",
    concepts: [
      {
        items: [
          "SI = P × r × t ÷ 100, and Amount = P + SI. Simple interest is the same every year.",
          "CI amount A = P(1 + r/100)ⁿ, and CI = A − P.",
          "Half-yearly compounding: rate r/2 per period, 2n periods. Quarterly: r/4 per period, 4n periods.",
          "CI − SI over 2 years = P(r/100)². Over 3 years = P(r/100)² × (3 + r/100).",
          "Amounts in successive years form a GP: Aₙ₊₁ ÷ Aₙ = 1 + r/100.",
          "Year-2 CI minus year-1 CI is the interest on year-1 interest, so r = (CI₂ − CI₁) ÷ CI₁ × 100.",
          "Doubling: under SI, money doubles in 100/r years. Under CI, if it doubles in n years it becomes 4× in 2n and 8× in 3n; the rule of 72 gives the doubling time as about 72/r years.",
          "Equal annual instalments X repaying a loan P at r% CI: P = X/(1 + r/100) + X/(1 + r/100)² + …, one term per instalment.",
          "The two formulas to know by heart:",
        ],
        tex: [
          String.raw`A = P\left(1 + \frac{r}{100}\right)^{n}`,
          String.raw`CI_{2\,\text{yr}} - SI_{2\,\text{yr}} = P\left(\frac{r}{100}\right)^{2}`,
        ],
      },
    ],
    thought: [
      "Identify SI or CI, and the compounding period.",
      "Turn rates into factors: 10% → 11/10, 20% → 6/5, 25% → 5/4, 12.5% → 9/8.",
      "For split investments, alligate on the rates (Section 10).",
      "For comparisons, set the two amounts equal and cancel common factors before multiplying anything out.",
    ],
    patterns: [
      "Split investment: total interest given; find how the money was split (alligation on rates).",
      "CI − SI gap for 2 or 3 years; find P or r.",
      "CI and SI for the same 2 years: r = 2 × (CI − SI) ÷ SI × 100, then P.",
      "Amounts after n and n + 1 years: their ratio is 1 + r/100.",
      "Two investors, two schemes: equal or related final amounts; find a principal.",
      "Equal instalments: a loan repaid in 2 or 3 equal annual payments.",
      "Doubling and tripling times under SI or CI.",
      "Different rates in different years: multiply the factors (1 + r₁/100)(1 + r₂/100)(1 + r₃/100).",
    ],
    examples: [
      { tag: "split investment", q: "Priya invests ₹50,000, part at 6% and the rest at 10% simple interest. Her total interest after one year is ₹3,800. How much did she invest at 10%?", a: "Average rate = 3,800/50,000 = 7.6%. Alligation: 6% part : 10% part = (10 − 7.6) : (7.6 − 6) = 3 : 2. The 10% part is 2/5 of 50,000. Check: 1,800 + 2,000 = 3,800. Answer: ₹20,000." },
      { tag: "CI − SI gap", q: "The difference between CI and SI on a sum for 2 years at 8% is ₹128. Find the sum.", a: "P × 0.08² = P × 0.0064 = 128. Answer: ₹20,000." },
      { tag: "CI and SI given", q: "On a sum, the SI for 2 years is ₹2,400 and the CI for 2 years is ₹2,520. Find the rate and the sum.", a: "SI per year = 1,200. The extra 120 is one year’s interest on 1,200, so r = 10%. P = 1,200 ÷ 0.10. Answer: 10%; ₹12,000." },
      { tag: "successive amounts", q: "A sum at CI grows to ₹13,310 in 3 years and ₹14,641 in 4 years. Find the rate and the sum.", a: "14,641/13,310 = 1.1, so r = 10%. P = 13,310 ÷ 1.331. Answer: 10%; ₹10,000." },
      { tag: "half-yearly", q: "₹40,000 is invested at 10% a year, compounded half-yearly, for 1 year. Find the amount.", a: "5% per half-year for 2 periods: 40,000 × 1.05² = 40,000 × 1.1025. Answer: ₹44,100 (interest ₹4,100, against ₹4,000 with yearly compounding)." },
      { tag: "equal instalments", q: "A loan of ₹21,000 is repaid in 2 equal annual instalments at 10% CI. Find each instalment.", a: "X/1.1 + X/1.21 = 21,000, so X × 2.1/1.21 = 21,000 and X = 12,100. Check: after year 1 the debt is 23,100; paying 12,100 leaves 11,000, which grows to 12,100. Answer: ₹12,100." },
      { tag: "two investors", q: "Kabir invests ₹P at 8% CI for 2 years. Dev invests ₹10,000 more than Kabir at 8% SI for 2 years. Dev’s interest exceeds Kabir’s by ₹1,072. Find P.", a: "Kabir earns 0.1664P. Dev earns 0.16(P + 10,000) = 0.16P + 1,600. The gap 1,600 − 0.0064P = 1,072 gives P = 528/0.0064. Answer: ₹82,500." },
      { tag: "doubling", q: "A sum doubles in 5 years at CI. When will it be 8 times? At what SI rate does a sum double in 8 years?", a: "8 = 2³, so three doubling periods. Under SI, doubling means total interest = P, so r × 8 = 100. Answer: 15 years; 12.5%." },
    ],
    traps: [
      "Half-yearly compounding: halve the rate and double the periods. Doing only one is the most common error.",
      "“Interest in the 3rd year” is not “interest for 3 years”.",
      "In instalment questions, discount each payment separately; never split the loan equally.",
      "Under SI, reaching 3× takes twice as long as reaching 2×. Under CI, the multiples compound.",
    ],
    practice: [
      { q: "Find the SI on ₹8,000 at 7.5% for 4 years.", a: "₹2,400: 8,000 × 0.075 × 4." },
      { q: "Find the CI on ₹15,625 at 8% for 2 years.", a: "₹2,600: 15,625 × 0.1664." },
      { q: "Find CI − SI on ₹10,000 at 10% for 3 years.", a: "₹310: 10,000 × 0.01 × 3.1 (CI 3,310 against SI 3,000)." },
      { q: "A sum at SI becomes ₹9,800 in 5 years and ₹12,005 in 8 years. Find the rate.", a: "12%: 3 years of SI = 2,205, so 735 a year; P = 9,800 − 5 × 735 = 6,125; 735/6,125 = 0.12." },
      { q: "₹1,00,000 is split between 5% and 8% SI and earns ₹6,800 a year. How much is at 8%?", a: "₹60,000: average 6.8%, so 5% : 8% = 1.2 : 1.8 = 2 : 3." },
      { q: "A city grows 5% a year and now has 4,41,000 people. What was its population two years ago?", a: "4,00,000: 4,41,000 ÷ 1.1025." },
      { q: "On the same principal at annual CI, the interest for year 1 is ₹500 and for year 2 is ₹550. Find the rate and principal.", a: "10% and ₹5,000: 50/500 = 10%, and 500 ÷ 0.1." },
    ],
  },
  {
    n: 8,
    slug: "ratio-proportion",
    title: "Ratio, Proportion, Partnership & Variation",
    short: "Ratio & Proportion",
    group: "Arithmetic",
    lede: "Ratio hides inside ages, incomes, coins, mixtures and fruit-seller stories, so it shows up in nearly every paper. The one move to master: write every quantity as “parts × k”, then find what stays constant.",
    asked:
      "Quantities in a ratio change (people join, items are sold, years pass) and a new ratio is given; you find the original or final numbers. Partnership shares, coin values, incomes against expenses and “partly fixed, partly variable” costs also recur. Answers usually must be whole numbers, which is itself a clue.",
    concepts: [
      {
        items: [
          "a : b = ka : kb. Write A = ak and B = bk.",
          "Combine ratios through the common term: A : B = 3 : 4 and B : C = 6 : 7 → make B equal (12) → 9 : 12 : 14.",
          "If a/b = c/d = e/f = k, then (a + c + e)/(b + d + f) = k as well.",
          "Componendo-dividendo: if a/b = c/d, then (a + b)/(a − b) = (c + d)/(c − d).",
          "Proportion a : b :: c : d means ad = bc. The mean proportional of a and b is √(ab).",
          "Partnership: profit share is proportional to capital × time.",
          "Variation: direct y = kx; inverse y = k/x; joint z = kxy; “partly fixed, partly variable” C = F + vn.",
          "Ages: the difference between two people’s ages never changes.",
          "2A = 3B = 4C means A : B : C = 1/2 : 1/3 : 1/4 = 6 : 4 : 3 (multiply through by 12).",
        ],
      },
    ],
    thought: [
      "Write each quantity as parts × k. Use a different multiplier for each unrelated ratio.",
      "Find what stays constant: an age gap, a component nobody touched, a total.",
      "Equate before and after through that constant, then solve for k.",
      "Check that the answer gives whole numbers where it must (people, coins, fruits).",
    ],
    patterns: [
      "Combining ratios through a common term.",
      "Before/after changes: students join, fruits are sold, water is added; a new ratio is given.",
      "Incomes and expenditures in ratios, with savings given.",
      "Coins and notes: the number ratio differs from the value ratio.",
      "Partnership: capital × months; partners joining late or leaving early; a working partner’s salary paid first.",
      "Variation: fixed + variable cost; inverse or inverse-square relations.",
      "Ages: ratios now, n years ago and n years hence.",
      "Integer clues: totals must be multiples of the ratio sum; count the possible values.",
    ],
    examples: [
      { tag: "combining", q: "A : B = 3 : 4 and B : C = 6 : 7. Find A : B : C.", a: "Make B = 12. A : B = 9 : 12 and B : C = 12 : 14. Answer: 9 : 12 : 14." },
      { tag: "incomes and expenditures", q: "The incomes of X and Y are in the ratio 5 : 4 and their expenditures 3 : 2. Each saves ₹8,000. Find X’s income.", a: "5k − 3m = 8,000 and 4k − 2m = 8,000. The second gives m = 2k − 4,000; substituting, 5k − 6k + 12,000 = 8,000, so k = 4,000. Check: X spends 12,000; Y earns 16,000 and spends 8,000. Answer: ₹20,000." },
      { tag: "before/after", q: "Two classes are in the ratio 7 : 5. After 12 students join the smaller class, the ratio becomes 7 : 6. How big was the larger class?", a: "The larger class did not change and is 7 parts in both ratios, so the parts are the same size. The smaller class went from 5 to 6 parts, so 1 part = 12. Answer: 84." },
      { tag: "ages", q: "Ten years ago, a father’s and son’s ages were in the ratio 5 : 1. Ten years from now they will be 7 : 3. Find the father’s present age.", a: "The age gap is 4 parts in both ratios, so the parts are equal. The father’s 7 parts later = his 5 parts earlier + 20 years, so 2 parts = 20 and 1 part = 10. Father now = 50 + 10. Check: 50 : 10 and 70 : 30. Answer: 60." },
      { tag: "partnership", q: "A starts a business with ₹60,000. B joins after 4 months with ₹80,000, and C joins after 7 months with ₹1,00,000. The year’s profit is ₹93,000. Find C’s share.", a: "Capital × months (in thousands): A = 60 × 12 = 720, B = 80 × 8 = 640, C = 100 × 5 = 500; total 1,860. C’s share = 500/1,860 × 93,000. Answer: ₹25,000." },
      { tag: "coins", q: "A bag holds ₹1, 50p and 25p coins in the ratio 2 : 3 : 4 by number, worth ₹216 in total. How many 25p coins are there?", a: "One set of 2 + 3 + 4 coins is worth 2 + 1.5 + 1 = ₹4.50. Sets = 216 ÷ 4.5 = 48. Answer: 192." },
      { tag: "variation", q: "A school bus costs ₹19,000 a month for 30 students and ₹25,000 for 50; the cost is partly fixed and partly per student. What is the cost for 70 students?", a: "20 more students cost 6,000, so ₹300 each; fixed cost = 19,000 − 9,000 = 10,000. For 70: 10,000 + 21,000. Answer: ₹31,000." },
      { tag: "integer clue", q: "A basket has apples and oranges in the ratio 5 : 3. After 13 apples and 3 oranges are sold, the ratio becomes 3 : 2. How many fruits were there at first?", a: "(5k − 13)/(3k − 3) = 3/2, so 10k − 26 = 9k − 9 and k = 17. Initially 85 + 51. Check: 72 : 48 = 3 : 2. Answer: 136." },
    ],
    traps: [
      "Age ratios change over time; age gaps do not.",
      "In partnership, multiply capital by time.",
      "In coin questions, the number ratio is not the value ratio.",
      "Never reuse the same k for two different ratio statements.",
    ],
    practice: [
      { q: "Divide ₹7,800 among A, B and C so that 2A = 3B = 4C. Find C’s share.", a: "₹1,800: the ratio is 6 : 4 : 3, so C = 3/13 × 7,800." },
      { q: "A : B = 2 : 3, B : C = 4 : 5 and C : D = 6 : 7. Find A : D.", a: "16 : 35: 2/3 × 4/5 × 6/7 = 48/105." },
      { q: "Two numbers are in the ratio 3 : 5. Subtracting 9 from each gives the ratio 12 : 23. Find the smaller number.", a: "33: 69k − 207 = 60k − 108 gives k = 11." },
      { q: "The incomes of P and Q are in the ratio 3 : 2 and their expenditures 5 : 3. Each saves ₹2,000. Find P’s income.", a: "₹12,000: from 3k − 5m = 2,000 and 2k − 3m = 2,000, m = 2,000 and k = 4,000." },
      { q: "A and B invest in the ratio 3 : 5 for 8 and 6 months respectively. Find their profit-sharing ratio.", a: "4 : 5: 24 : 30." },
      { q: "y varies inversely as x², and y = 8 when x = 3. Find y when x = 6.", a: "2: k = 8 × 9 = 72, and 72/36 = 2." },
      { q: "Find the mean proportional of 9 and 16.", a: "12: √144." },
    ],
  },
  {
    n: 9,
    slug: "averages",
    title: "Averages",
    short: "Averages",
    group: "Arithmetic",
    lede: "Every averages question gets easy once you convert averages into totals: sum = average × count. CAT’s favourite twist is optimisation, the largest or smallest possible value under an average and a few constraints.",
    asked:
      "Members join or leave a group; a wrong entry is corrected; two groups’ averages change between two tests; averages of terms in a progression; and “what is the maximum possible value of…” questions with integer or distinctness constraints.",
    concepts: [
      {
        items: [
          "Sum = average × count. Work in sums, not averages.",
          "A member joins: new member = old average + (change in average × new count).",
          "Replacement: incoming − outgoing = change in average × count.",
          "Weighted average = (n₁a₁ + n₂a₂) ÷ (n₁ + n₂). It lies between a₁ and a₂, closer to the bigger group.",
          "Average of an AP = (first + last) ÷ 2 = the middle term.",
          "Adding k to every value adds k to the average; multiplying every value by k multiplies the average by k.",
          "Ages: everyone gets one year older each year, so a family’s total age rises by members × years.",
          "Optimisation rule: to maximise one value, push all the others as low as the constraints allow, and vice versa.",
        ],
      },
    ],
    thought: [
      "Convert every average into a total.",
      "Write what changed between the “before” and “after” totals.",
      "For max/min questions, list the constraints (integer? distinct? positive? an upper limit?) and push the other values to their extremes.",
    ],
    patterns: [
      "Joining, leaving and replacement.",
      "A wrong entry corrected.",
      "Weighted average of groups: sections, boys and girls.",
      "Two groups across two tests: use totals, and watch for data that does not matter.",
      "Optimisation: the max/min of one value, or of the median, given an average and constraints.",
      "Averages of AP terms or of numbers in a range with a property.",
      "Cricket: runs needed to lift a batting average.",
      "Ages over time, with members added.",
    ],
    examples: [
      { tag: "joining", q: "The average weight of 24 students is 50 kg. Including the teacher raises the average by 1 kg. Find the teacher’s weight.", a: "Teacher = 50 + 1 × 25. Check: 25 × 51 = 1,275 = 1,200 + 75. Answer: 75 kg." },
      { tag: "replacement", q: "The average age of 8 men rises by 2 years when two men aged 20 and 24 are replaced by two women. Find the women’s average age.", a: "The total rises by 8 × 2 = 16, so the women total 44 + 16 = 60. Answer: 30 years." },
      { tag: "wrong entry", q: "The average of 40 numbers was found to be 35, but 83 had been misread as 38. Find the correct average.", a: "The total rises by 45, so the average rises by 45/40 = 1.125. Answer: 36.125." },
      { tag: "weighted", q: "Section A has 30 students averaging 60 and section B has 20 averaging 75. Find the overall average.", a: "(1,800 + 1,500) ÷ 50. Answer: 66." },
      { tag: "two tests", q: "A class has 30 boys and 20 girls. In Test 1 the girls averaged 6 marks more than the boys. In Test 2 the girls’ average fell by 2 while the class average rose by 1. By how much did the boys’ average change?", a: "Class total change = 50 × 1 = +50. Girls’ total change = 20 × (−2) = −40. So the boys’ total rose by 90, which is 90/30 = 3 per boy. The “6 more” was never needed; CAT often adds such data. Answer: up by 3." },
      { tag: "optimisation, maximum", q: "The average of 5 distinct positive integers is 20. What is the largest possible value of the largest one?", a: "Sum = 100. Make the other four as small as possible: 1 + 2 + 3 + 4 = 10. Answer: 90." },
      { tag: "optimisation, median", q: "The average of 7 distinct positive integers is 12. What is the largest possible median?", a: "Sum = 84. The smallest three are 1, 2, 3. With median m, the top three are at least m + 1, m + 2, m + 3. So 6 + m + 3m + 6 = 84 and m = 18. Check: 1, 2, 3, 18, 19, 20, 21 sums to 84. Answer: 18." },
      { tag: "AP average", q: "Find the average of all three-digit numbers that leave remainder 2 when divided by 7.", a: "They form an AP from 100 (= 98 + 2) to 996 (= 994 + 2). Average = (100 + 996) ÷ 2. Answer: 548." },
      { tag: "cricket", q: "A batter averages 40 after 20 innings. How many runs must she score in the 21st innings to raise her average to 42?", a: "40 + 2 × 21. Check: 42 × 21 = 882 = 800 + 82. Answer: 82." },
      { tag: "ages over time", q: "Four years ago, a family of 5 had an average age of 30. A baby has been born since, and the 6 members now average 28.5 years. How old is the baby?", a: "The original 5 now total 150 + 5 × 4 = 170. The family of 6 totals 6 × 28.5 = 171. Answer: 1 year." },
    ],
    traps: [
      "Averaging two averages when the groups differ in size.",
      "Forgetting the extra year per person per year in age questions.",
      "Ignoring “distinct” or “positive” in optimisation; those words decide the answer.",
    ],
    practice: [
      { q: "The average of 11 numbers is 50. The first 6 average 49 and the last 6 average 52. Find the 6th number.", a: "56: 294 + 312 − 550, since the 6th number is counted in both groups." },
      { q: "The average of 5 consecutive odd numbers is 61. Find the largest.", a: "65: the middle number is 61." },
      { q: "50 students average 40 marks. 10 students averaging 52 leave. Find the new average.", a: "37: (2,000 − 520) ÷ 40." },
      { q: "The average of a, b, c is 20 and of b, c, d is 25. If d = 30, find a.", a: "15: (a + b + c) − (b + c + d) = 60 − 75, so a = d − 15." },
      { q: "The mean of 6 distinct positive integers is 15. What is the largest possible value of the largest one?", a: "75: 90 − (1 + 2 + 3 + 4 + 5)." },
      { q: "11 players average 26 years. Without the captain, the rest average 25. Find the captain’s age.", a: "36: 286 − 250." },
    ],
  },
  {
    n: 10,
    slug: "mixtures-alligation",
    title: "Mixtures & Alligation",
    short: "Mixtures",
    group: "Arithmetic",
    lede: "Mixture questions reduce to two tools: alligation for mixing two things, and the replacement formula for “remove and refill” cycles. Alligation also speeds up averages, profit and interest questions, so it pays twice.",
    asked:
      "Two solutions mixed in a ratio; repeated draw-and-replace; water added or evaporated to reach a ratio; multi-step mixing (A with B, then more A); alloys of gold and copper; and alligation disguised as speeds or profits.",
    concepts: [
      {
        items: ["Alligation: mixing quantity q₁ of value c₁ with q₂ of value c₂ gives mean m when"],
        tex: [String.raw`\frac{q_1}{q_2} = \frac{c_2 - m}{m - c_1}`],
      },
      {
        items: [
          "In words: each part’s weight is the distance of the other part’s value from the mean. The mean always lies between c₁ and c₂.",
          "The ratio is in the unit the value is measured per: litres for concentration per litre, kg for price per kg, hours for speed in km per hour.",
          "Replacement: from V litres of pure liquid, remove x litres and refill with water, n times. The pure liquid left is",
        ],
        tex: [String.raw`V\left(1 - \frac{x}{V}\right)^{n}`],
      },
      {
        items: [
          "Adding or evaporating water changes the total but not the solute. Track the component that does not change.",
          "With three or more components, track each component’s quantity separately.",
        ],
      },
    ],
    thought: [
      "Decide what is being averaged (concentration? price per kg?) and per what unit.",
      "Identify the component that stays constant.",
      "Two-part mix → alligation. Multi-step mix → track each component in a small table.",
      "Sanity check: the mix’s value must lie between the two inputs.",
    ],
    patterns: [
      "Two solutions mixed: find the result’s concentration, or the ratio that hits a target.",
      "Repeated replacement: the amount left, or how many cycles before it falls below a level.",
      "Add water or evaporate to reach a target ratio.",
      "Multi-step mixing: A with B, then the result with more A.",
      "Alloys: ratios of metals; equal masses of two alloys melted together.",
      "Selling a mixture at a profit: find the cost of the mix first, then alligate.",
      "Alligation outside mixtures: average speeds (weights are times), profit percentages, interest rates, group averages.",
    ],
    examples: [
      { tag: "basic alligation", q: "Rice at ₹40/kg and ₹60/kg is mixed so that the blend costs ₹52/kg. In what ratio?", a: "(60 − 52) : (52 − 40) = 8 : 12. Answer: 2 : 3 (cheaper : dearer)." },
      { tag: "mix + profit", q: "Tea at ₹300/kg and ₹400/kg is blended and sold at ₹420/kg for a 20% profit. In what ratio was it blended?", a: "Cost of the blend = 420 ÷ 1.2 = 350. (400 − 350) : (350 − 300) = 50 : 50. Answer: 1 : 1." },
      { tag: "adding water", q: "30 L of a mixture has milk : water = 7 : 3. How much water must be added to make it 3 : 2?", a: "Milk stays at 21 L. For 3 : 2, water must be 21 × 2/3 = 14 L; there are 9 L now. Answer: 5 L." },
      { tag: "replacement", q: "A 50 L container is full of juice. 10 L are removed and replaced with water; this is done 3 times in all. How much juice remains?", a: "50 × (4/5)³ = 50 × 64/125. Answer: 25.6 L." },
      { tag: "threshold", q: "A 30 L jar of pure milk has 5 L removed and replaced with water each time. After how many operations is milk first less than half?", a: "Each cycle keeps 5/6 of the milk. (5/6)³ = 125/216 ≈ 0.58; (5/6)⁴ = 625/1296 ≈ 0.48. Answer: 4." },
      { tag: "two-step mixing", q: "Solution A is 30% acid and B’s strength is unknown. A and B are mixed 1 : 2, then a volume of A equal to that mixture is added. The final mixture is 40% acid. Find B’s strength.", a: "Units: A 1 and B 2, then 3 more of A, so A 4 and B 2 out of 6. Acid: 4 × 0.3 + 2b = 6 × 0.4, so 1.2 + 2b = 2.4 and b = 0.6. Answer: 60%." },
      { tag: "alloys", q: "Alloy P has gold : copper = 3 : 2 and alloy Q has 1 : 3. Equal masses are melted together. Find the new ratio.", a: "Take 20 kg of each (the LCM of 5 and 4). P gives 12 gold and 8 copper; Q gives 5 gold and 15 copper. Answer: 17 : 23." },
      { tag: "evaporation", q: "40 kg of salt water is 4% salt. How much water must evaporate to make it 10% salt?", a: "Salt stays at 1.6 kg, so the new total is 1.6 ÷ 0.10 = 16 kg. Answer: 24 kg." },
      { tag: "alligation on speed", q: "A man covers 300 km in 6 hours, partly by car at 60 km/h and partly by bus at 40 km/h. How far did he go by car?", a: "Average speed = 50 km/h. Speeds average by time, so car time : bus time = (50 − 40) : (60 − 50) = 1 : 1, or 3 hours each. Check: 180/60 + 120/40 = 6. Answer: 180 km." },
    ],
    traps: [
      "Alligating speeds by distance. Average speed weights speeds by time.",
      "Using the replacement formula when the amount removed changes between cycles, or the refill is not the pure “other” liquid.",
      "Forgetting to recompute both components after adding more of a mixture.",
    ],
    practice: [
      { q: "12 L of 25% alcohol is mixed with 8 L of 40% alcohol. Find the concentration.", a: "31%: (3 + 3.2) ÷ 20." },
      { q: "How much pure alcohol must be added to 30 L of a 20% solution to make it 40%?", a: "10 L: (6 + x)/(30 + x) = 0.4." },
      { q: "From an 80 L cask of wine, 8 L are drawn and replaced with water, twice. How much wine is left?", a: "64.8 L: 80 × 0.9²." },
      { q: "Two vessels have milk : water = 3 : 1 and 5 : 3. In what ratio should they be mixed to get 2 : 1?", a: "1 : 2 (first : second): the milk fractions are 18/24 and 15/24 against a target of 16/24, so first : second = (16 − 15) : (18 − 16)." },
      { q: "Pulses at ₹90/kg and ₹120/kg are mixed 2 : 1. At what price should the mix sell for a 25% profit?", a: "₹125/kg: the mix costs (180 + 120) ÷ 3 = 100." },
      { q: "Alloy A (copper : zinc = 3 : 2) and alloy B (4 : 1) are mixed 1 : 1 by mass. What percent is copper?", a: "70%: the average of 60% and 80%." },
    ],
  },
  {
    n: 11,
    slug: "time-work",
    title: "Time & Work (with Pipes & Cisterns)",
    short: "Time & Work",
    group: "Arithmetic",
    lede: "Turn every time into a rate with the LCM trick and most work questions become simple addition. CAT’s versions add people joining or leaving midway, efficiency comparisons, leaks and wages.",
    asked:
      "Workers with different speeds finish a job in phases; pipes fill and leaks empty a tank opened at different times; “A is 50% more efficient than B”; men–women–children equivalence; wages split by work done; workers who alternate days or drop out.",
    concepts: [
      {
        items: [
          "If A finishes a job in a days, A’s rate is 1/a of the job per day. Rates add when people work together.",
          "LCM trick: total work = LCM of the individual times, so rates become whole units per day. A in 12 days and B in 18 days: work = 36 units, A = 3 and B = 2 per day, together 5, so 36/5 = 7.2 days.",
          "Efficiency is the inverse of time: if A is twice as efficient as B, A takes half the time.",
          "Man-days: men × days × hours per unit of work stays constant.",
          "Pipes: inlets add, outlets and leaks subtract.",
          "Wages are proportional to work done, not days present.",
          "Alternate days: find one cycle’s work, count the full cycles, then finish the leftover.",
          "The man-days relation:",
        ],
        tex: [String.raw`\frac{M_1 D_1 H_1}{W_1} = \frac{M_2 D_2 H_2}{W_2}`],
      },
    ],
    thought: [
      "Set total work = LCM of the given times and write each worker’s rate in units per day.",
      "Split the timeline into phases, each with a fixed set of workers.",
      "The work in all phases adds up to the total; solve for the unknown time.",
      "If someone leaves “x days before completion”, work backwards from the end.",
    ],
    patterns: [
      "Combined work, then someone leaves or joins.",
      "Pair sums: A + B in x days, B + C in y, C + A in z. Adding all three gives twice the total rate.",
      "Efficiency statements: “50% more efficient” means rates in the ratio 3 : 2.",
      "Man-days and equivalences between men, women and children.",
      "Pipes and leaks, including pipes opened or closed at different times.",
      "Alternate-day cycles.",
      "Wages split by work done.",
      "A changing workforce, such as one worker leaving each day (an AP sum).",
    ],
    examples: [
      { tag: "LCM + leaving", q: "A can finish a job in 12 days and B in 15. They work together for 4 days, then A leaves. How long does B take to finish?", a: "Work = 60 units; A = 5 and B = 4 per day. Four days together = 36 units, leaving 24 for B at 4 a day. Answer: 6 more days (10 in total)." },
      { tag: "pair sums", q: "A + B finish in 10 days, B + C in 12 and C + A in 15. How long would A take alone?", a: "Work = 60. A + B = 6, B + C = 5, C + A = 4, so 2(A + B + C) = 15 and A + B + C = 7.5. A = 7.5 − 5 = 2.5 a day. Answer: 24 days." },
      { tag: "efficiency", q: "A is 50% more efficient than B. Together they finish in 18 days. How long would A take alone?", a: "A : B = 3 : 2, so 5 units a day for 18 days = 90 units. A alone: 90 ÷ 3. Answer: 30 days." },
      { tag: "man-days", q: "12 men working 8 hours a day build a wall in 10 days. How many days would 16 men working 6 hours a day take to build a wall twice as long?", a: "12 × 8 × 10 ÷ 1 = 16 × 6 × D ÷ 2, so 960 = 48D. Answer: 20 days." },
      { tag: "leak", q: "A pipe fills a tank in 6 hours; with a leak it takes 8 hours. How long would the leak alone take to empty a full tank?", a: "Work = 24. The pipe adds 4 an hour and the net is 3, so the leak removes 1 an hour. Answer: 24 hours." },
      { tag: "pipe closed midway", q: "Pipe P fills a tank in 20 minutes and Q in 30. Both are opened, Q is closed after a while, and the tank fills in 15 minutes in total. When was Q closed?", a: "Work = 60; P = 3 and Q = 2 per minute. P alone does 45 in 15 minutes, so Q contributed 15 at 2 a minute. Answer: after 7.5 minutes." },
      { tag: "alternate days", q: "A finishes a job in 10 days and B in 15. They work on alternate days, A first. How many days does the job take?", a: "Work = 30; A = 3, B = 2, so each 2-day cycle does 5. After 10 days, 25 is done. Day 11 (A) reaches 28 and day 12 (B) reaches 30. Answer: 12 days." },
      { tag: "wages", q: "A, B and C can finish a job in 6, 8 and 12 days. Working together, they are paid ₹3,600. Find C’s share.", a: "Work = 24; rates 4, 3 and 2 (total 9). C’s share = 2/9 × 3,600. Answer: ₹800." },
      { tag: "shrinking team", q: "10 workers start a 45-unit job, each doing 1 unit a day, and one worker leaves at the end of each day. How many days does the job take?", a: "10 + 9 + 8 + 7 + 6 + 5 = 45. Answer: 6 days." },
    ],
    traps: [
      "Treating a leak as positive work.",
      "Splitting wages by days present instead of work done.",
      "“Leaves 3 days before completion”: the leaver worked (total − 3) days. Work backwards from the end.",
    ],
    practice: [
      { q: "A can do a job in 20 days and B in 30. How long together?", a: "12 days: 60 units at 3 + 2 a day." },
      { q: "A and B together take 12 days, and A alone takes 20. How long does B alone take?", a: "30 days: 60 units, A + B = 5 and A = 3, so B = 2." },
      { q: "Two pipes fill a tank in 10 and 15 hours; a third empties it in 20 hours. With all three open, how long does it take to fill?", a: "8 4/7 hours: 60 units at 6 + 4 − 3 = 7 an hour." },
      { q: "6 men or 10 women can finish a job in 15 days. How long will 3 men and 5 women take?", a: "15 days: 3 men = 5 women, so the team equals 10 women." },
      { q: "A works twice as fast as B, and together they take 12 days. How long does B alone take?", a: "36 days: rates 2 : 1 and 36 units in total." },
      { q: "A + B take 8 days, B + C take 12 and A + B + C take 6. How long do A and C take together?", a: "8 days: 24 units; A + B + C = 4 and B + C = 2 give A = 2; A + B = 3 gives B = 1, so C = 1 and A + C = 3." },
    ],
  },
  {
    n: 12,
    slug: "time-speed-distance",
    title: "Time, Speed & Distance",
    short: "TSD",
    group: "Arithmetic",
    lede: "TSD is one of CAT’s most frequent arithmetic chapters and usually its trickiest. Nearly all of it runs on D = S × T, relative speed, and the habit of holding one quantity fixed so you can work in ratios.",
    asked:
      "Two people or trains start from different points, often at different times, and meet; a speed change makes someone late or early; average speed over several legs; trains passing poles, platforms, walkers and each other; boats in a current; races with head starts; runners on circular tracks; buses with stoppages.",
    concepts: [
      {
        items: [
          "D = S × T. Convert units first: km/h × 5/18 = m/s, and m/s × 18/5 = km/h.",
          "Fixed distance: speed and time are inversely proportional. Fixed time: distance is proportional to speed.",
          "Average speed = total distance ÷ total time. Equal times at speeds a and b give (a + b)/2.",
          "Relative speed: add for opposite directions, subtract for the same direction.",
          "Trains: passing a pole or a standing person takes length ÷ speed. Passing a platform or another train takes (sum of lengths) ÷ relative speed.",
          "Boats: downstream = b + s and upstream = b − s, so b = (down + up)/2 and s = (down − up)/2.",
          "Races: “A beats B by x m in an L m race” means B has run L − x when A finishes, so their speeds are in the ratio L : (L − x).",
          "Circular track of length L, speeds a > b: first meeting after L/(a − b) in the same direction or L/(a + b) in opposite directions. First meeting at the start = LCM of the two lap times. With the speed ratio p : q in lowest terms, there are p − q distinct meeting points (same direction) or p + q (opposite).",
          "On a straight track where both turn back at the ends, by the second meeting they have together covered 3 times its length.",
          "Equal distances at speeds a and b, and the after-meeting rule (two start together towards each other and need t₁ and t₂ hours after meeting to finish; they met after √(t₁t₂) hours):",
        ],
        tex: [String.raw`\text{Average speed} = \frac{2ab}{a+b}`, String.raw`\frac{S_1}{S_2} = \sqrt{\frac{t_2}{t_1}}`],
      },
    ],
    thought: [
      "Draw a line: mark the starting points, directions and start times.",
      "Convert all units to one system.",
      "Decide what is fixed and use ratios (fixed distance → inverse speeds).",
      "Two moving bodies → relative speed. One moving body → its own speed.",
      "Check the answer against the story: who should be faster, who should arrive first?",
    ],
    patterns: [
      "Meeting point, often with one person starting later.",
      "After-meeting times → speed ratio through square roots.",
      "Late or early with a changed speed → distance or usual time.",
      "Average speed across legs.",
      "Trains: poles, platforms, walkers, other trains.",
      "Boats and streams.",
      "Races and head starts.",
      "Circular tracks: first meeting, first meeting at the start, number of meeting points.",
      "Ratio-only questions: “where do they meet?” needs only the speed ratio.",
      "Stoppages: minutes stopped per hour.",
      "To-and-fro trips and second meetings.",
    ],
    evidence:
      "In Cracku’s topic-wise TSD collection, the after-meeting square-root rule (pattern 2) appears in at least five slots between 2020 and 2024. Late/early trips (pattern 3) appear in 2017, 2020, 2024 and 2025; races (pattern 7) in 2017, 2019 and 2020; circular tracks (pattern 8) in 2019, 2020 and 2021; boats (pattern 6) in 2017, 2023 and 2025. An escalator question, a cousin of relative speed, appeared in 2022.",
    examples: [
      { tag: "late/early", q: "Walking at 4 km/h, Ravi reaches the station 10 minutes late; at 5 km/h he is 5 minutes early. How far is the station?", a: "The times differ by 15 minutes. Speeds 4 : 5 mean times 5 : 4, so 1 part = 15 minutes and the 4 km/h trip takes 75 minutes. Distance = 4 × 1.25. Answer: 5 km." },
      { tag: "delayed start", q: "P and Q are 210 km apart. A car leaves P at 8:00 a.m. at 50 km/h; another leaves Q at 9:00 a.m. at 30 km/h towards P. When and where do they meet?", a: "By 9:00 the first car has covered 50 km. The 160 km gap closes at 80 km/h, taking 2 hours. Answer: 11:00 a.m., 150 km from P." },
      { tag: "after-meeting times", q: "Two trains leave X and Y at the same time, heading towards each other. After meeting, the X-train takes 9 hours to reach Y and the Y-train takes 4 hours to reach X. Find the ratio of their speeds.", a: "Speed of X-train ÷ speed of Y-train = √(4/9) = 2/3, and they met after √(9 × 4) = 6 hours. Check with speeds 2 and 3: before meeting X covers 12 and Y covers 18; afterwards X needs 18/2 = 9 hours and Y needs 12/3 = 4. Answer: 2 : 3." },
      { tag: "average speed", q: "A car goes from A to B at 40 km/h and returns at 60 km/h. Find its average speed.", a: "Equal distances: 2 × 40 × 60 ÷ 100. Answer: 48 km/h." },
      { tag: "pole and platform", q: "A 240 m train passes a pole in 12 seconds. How long does it take to cross a 360 m platform?", a: "Speed = 20 m/s; it must cover 240 + 360 = 600 m. Answer: 30 seconds." },
      { tag: "trains passing walkers", q: "A train overtakes a jogger running at 6 km/h in 9 seconds and a cyclist riding at 12 km/h, in the same direction, in 10 seconds. Find the train’s speed and length.", a: "Length = (v − 6) × 5/18 × 9 = (v − 12) × 5/18 × 10, so 9v − 54 = 10v − 120 and v = 66 km/h. Length = 60 × 5/18 × 9 = 150 m. Check: 54 km/h = 15 m/s, and 15 × 10 = 150. Answer: 66 km/h; 150 m." },
      { tag: "boats", q: "A boat goes 30 km downstream in 2 hours and returns in 3 hours. Find the boat’s speed in still water and the stream’s speed.", a: "Downstream 15 km/h, upstream 10 km/h. Answer: boat 12.5 km/h; stream 2.5 km/h." },
      { tag: "races", q: "In a 1,000 m race, A beats B by 100 m and B beats C by 100 m. By how much does A beat C?", a: "When A runs 1,000, B runs 900. C runs 90% of whatever B runs, so 810. Answer: 190 m." },
      { tag: "circular track", q: "Two runners start together on a 600 m circular track at 5 m/s and 3 m/s in the same direction. When do they first meet, when do they first meet at the start, and at how many distinct points do they meet?", a: "Relative speed 2 m/s gives 600/2 = 300 s. Lap times are 120 s and 200 s, LCM 600 s. The speed ratio 5 : 3 gives 5 − 3 = 2 points (the start and the halfway mark). In opposite directions they would first meet after 600/8 = 75 s, at 5 + 3 = 8 points. Answer: 300 s; 600 s; 2 points." },
      { tag: "stoppages", q: "Excluding stops, a bus averages 54 km/h; including stops, 45 km/h. For how many minutes per hour does it stop?", a: "It loses 9 km of travel each hour, which takes 9/54 hour at full speed. Answer: 10 minutes." },
      { tag: "second meeting", q: "Two people start from opposite ends of a 1.6 km path at 5 km/h and 3 km/h, each turning back on reaching the far end. When and where do they meet for the second time?", a: "Together they cover 3 × 1.6 = 4.8 km at 8 km/h, taking 0.6 hours. The faster walker covers 3 km: 1.6 to the far end and 1.4 back, ending 0.2 km from his start. Check: the slower covers 1.8 km, reaching the faster walker’s end and coming 0.2 km back. Answer: after 36 minutes, 200 m from the faster walker’s start." },
    ],
    traps: [
      "The average of two speeds is not the average speed, unless the times are equal.",
      "Mixing metres with km/h.",
      "In races, “beats by t seconds” means the loser needs t more seconds at his own speed.",
      "“Meet at the start” on a circular track uses the LCM of lap times, not relative speed.",
    ],
    practice: [
      { q: "A man travels at 30 km/h and returns at 20 km/h, taking 5 hours in all. Find the one-way distance.", a: "60 km: D/30 + D/20 = D/12 = 5." },
      { q: "Trains 150 m and 100 m long run in opposite directions at 40 km/h and 50 km/h. How long do they take to cross each other?", a: "10 s: 250 m at 90 km/h = 25 m/s." },
      { q: "A boat’s speed in still water is 15 km/h and the stream’s is 3 km/h. How long does it take to go 36 km downstream and come back?", a: "5 hours: 36/18 + 36/12." },
      { q: "Walking at 3/4 of his usual speed, a man is 20 minutes late. What is his usual time?", a: "60 minutes: the time becomes 4/3 of usual, so the extra 1/3 is 20 minutes." },
      { q: "A and B start towards each other from 100 km apart at 30 km/h and 20 km/h. Where do they meet?", a: "60 km from A’s start: they meet after 2 hours." },
      { q: "Two runners start together on a 400 m circular track at 6 m/s and 4 m/s in opposite directions. When do they first meet, and when do they first meet at the start?", a: "40 s (400 ÷ 10) and 200 s (lap times of 200/3 s and 100 s; in 200 s they run exactly 3 and 2 laps)." },
      { q: "In a 200 m race, A beats B by 20 m or by 4 seconds. Find A’s time.", a: "36 s: B covers the last 20 m in 4 s, so B runs at 5 m/s and takes 40 s for the race; A finishes 4 s earlier." },
    ],
  },
  {
    n: 13,
    slug: "linear-quadratic-equations",
    title: "Linear & Quadratic Equations",
    short: "Equations",
    group: "Algebra",
    lede: "Linear and quadratic equations are the friendliest algebra in CAT: word problems become one or two equations, and most quadratic questions need only the sum and product of the roots. They also power the optimisation questions hidden in arithmetic.",
    asked:
      "Linear: word problems with two or three unknowns, sometimes with fewer equations than unknowns so only a combination can be found; test scores with negative marking; whole-number solutions of ax + by = c. Quadratic: expressions in the roots; conditions for real or integer roots; equations that turn quadratic after a substitution; the maximum or minimum of a quadratic.",
    concepts: [
      {
        title: "Linear",
        items: [
          "n unknowns usually need n independent equations.",
          "With fewer equations than unknowns, CAT asks for a combination (such as x + y + z). Add or subtract multiples of the given equations to build it.",
          "ax + by = c in whole numbers: find one solution, then step x by b/g and y by a/g in opposite directions, where g = HCF(a, b).",
          "For a₁x + b₁y = c₁ and a₂x + b₂y = c₂: one solution if a₁/a₂ ≠ b₁/b₂; none if a₁/a₂ = b₁/b₂ ≠ c₁/c₂; infinitely many if all three ratios are equal.",
        ],
      },
      {
        title: "Quadratic",
        items: ["The roots of ax² + bx + c = 0 are"],
        tex: [String.raw`x = \frac{-b \pm \sqrt{b^{2} - 4ac}}{2a}`],
      },
      {
        items: [
          "Sum of roots = −b/a; product of roots = c/a.",
          "Discriminant D = b² − 4ac: D > 0 gives two distinct real roots, D = 0 equal roots, D < 0 no real roots. With rational coefficients, rational roots need D to be a perfect square.",
          "The equation with roots α and β is x² − (α + β)x + αβ = 0.",
          "α² + β² = (α + β)² − 2αβ; (α − β)² = (α + β)² − 4αβ; α³ + β³ = (α + β)³ − 3αβ(α + β); 1/α + 1/β = (α + β)/αβ.",
          "Signs: product < 0 means one positive and one negative root; sum > 0 and product > 0 means both positive.",
          "ax² + bx + c is smallest at x = −b/2a when a > 0, and largest there when a < 0.",
          "Substitutions such as t = 2ˣ, t = x² or t = x + 1/x turn harder equations into quadratics.",
        ],
      },
    ],
    thought: [
      "Name the unknowns and write one equation per fact.",
      "Before solving, check what is asked: often a combination or an expression in the roots, not the roots themselves.",
      "For quadratics, use sum and product first; find the actual roots only if you must.",
      "Check the domain: counts must be whole and positive, and roots must be real when the story needs them.",
    ],
    patterns: [
      "Word problems → a linear system.",
      "Fewer equations than unknowns: the asked quantity is a combination.",
      "Whole-number solutions: ways to pay an amount with two kinds of coins.",
      "Scoring with negative marks.",
      "Expressions in the roots via sum and product.",
      "Conditions on roots: real, equal, integer, opposite signs, one root k more than the other.",
      "Equations that become quadratic after a substitution.",
      "Max/min of a quadratic, often hidden in a revenue or profit story (Section 6, Example 9).",
    ],
    examples: [
      { tag: "combination", q: "3 pens, 2 pencils and 1 eraser cost ₹52; 4 pens, 3 pencils and 2 erasers cost ₹75. What do one pen, one pencil and one eraser cost together?", a: "Subtract the first equation from the second: p + q + r = 75 − 52. Answer: ₹23." },
      { tag: "scoring", q: "A test gives +4 for a correct answer and −1 for a wrong one. Asha attempts 60 questions and scores 160. How many did she get right?", a: "c + w = 60 and 4c − w = 160. Adding, 5c = 220. Answer: 44." },
      { tag: "whole-number solutions", q: "In how many ways can ₹100 be paid with ₹5 and ₹2 coins, using at least one of each?", a: "5x + 2y = 100 needs x even: x = 2, 4, …, 18 (x = 20 would leave y = 0). Answer: 9 ways." },
      { tag: "ages", q: "A mother’s and daughter’s ages add to 50. Five years ago the mother was 7 times as old as the daughter. Find their present ages.", a: "M − 5 = 7(D − 5) and M = 50 − D, so 45 − D = 7D − 35 and D = 10. Answer: 40 and 10." },
      { tag: "consistency", q: "For what k do 2x + 3y = 7 and 4x + ky = 14 have infinitely many solutions?", a: "Need 2/4 = 3/k = 7/14. Answer: k = 6." },
      { tag: "expression in roots", q: "α and β are the roots of x² − 7x + 10 = 0. Find α² + β².", a: "(α + β)² − 2αβ = 49 − 20. Check: the roots are 2 and 5, and 4 + 25 = 29. Answer: 29." },
      { tag: "root condition", q: "One root of x² − 11x + k = 0 is 3 more than the other. Find k.", a: "Roots r and r + 3 add to 11, so r = 4 and the roots are 4 and 7. k = product. Answer: 28." },
      { tag: "counting real-root cases", q: "For how many integers k with |k| ≤ 10 does x² + kx + 16 = 0 have real roots?", a: "Need k² − 64 ≥ 0, so |k| ≥ 8: k = ±8, ±9, ±10. Answer: 6." },
      { tag: "substitution", q: "Solve 4ˣ − 6 × 2ˣ + 8 = 0.", a: "With t = 2ˣ, t² − 6t + 8 = 0, so t = 2 or 4. Answer: x = 1 or x = 2." },
      { tag: "minimum", q: "Find the minimum value of x² − 6x + 14.", a: "x² − 6x + 14 = (x − 3)² + 5, which is smallest at x = 3. Answer: 5." },
    ],
    traps: [
      "Solving for every variable when only a combination is asked; it wastes time and is sometimes impossible.",
      "Sum of roots is −b/a, not b/a.",
      "Ignoring the domain: negative people, fractional coins, roots that must be real.",
    ],
    practice: [
      { q: "Find the equation whose roots are the reciprocals of the roots of 2x² − 5x + 3 = 0.", a: "3x² − 5x + 2 = 0: replace x by 1/x and clear the fractions." },
      { q: "α and β are the roots of x² − 5x + 3 = 0. Find 1/α + 1/β.", a: "5/3: sum ÷ product." },
      { q: "5 chairs and 3 tables cost ₹2,900; 3 chairs and 5 tables cost ₹3,500. What do one chair and one table cost together?", a: "₹800: adding gives 8 chairs + 8 tables = 6,400." },
      { q: "How many non-negative whole-number solutions does 3x + 5y = 60 have?", a: "5: x must be a multiple of 5 from 0 to 20." },
      { q: "For what k does x² − 8x + k = 0 have equal roots?", a: "16: D = 64 − 4k = 0." },
      { q: "Solve 9ˣ − 4 × 3ˣ + 3 = 0.", a: "x = 0 or 1: with t = 3ˣ, t = 1 or 3." },
    ],
  },
  {
    n: 14,
    slug: "indices-surds-logarithms",
    title: "Indices, Surds & Logarithms",
    short: "Indices & Logs",
    group: "Algebra",
    lede: "These are rule-based chapters: learn about ten rules and most questions fall in under two minutes. Rewrite everything in prime bases for indices, and convert to a single base for logs.",
    asked:
      "Solve an exponential equation by matching bases; simplify a power expression; compare the sizes of surds or powers; simplify nested roots or telescoping sums; evaluate or solve log expressions, often through a change-of-base chain; count digits using log 2 and log 3.",
    concepts: [
      {
        title: "Indices and surds",
        items: [
          "aᵐ × aⁿ = aᵐ⁺ⁿ; aᵐ ÷ aⁿ = aᵐ⁻ⁿ; (aᵐ)ⁿ = aᵐⁿ; a⁰ = 1; a⁻ⁿ = 1/aⁿ; a^(1/n) is the n-th root of a. (ab)ⁿ = aⁿbⁿ.",
          "If aˣ = aʸ (a > 0, a ≠ 1), then x = y. If aˣ = bˣ with a ≠ b (both positive), then x = 0.",
          "Rewrite in prime bases: 8 = 2³, 27 = 3³, 125 = 5³, 0.25 = 2⁻².",
          "Rationalise: 1/(√a + √b) = (√a − √b)/(a − b).",
          "Nested roots: √(a + 2√b) = √x + √y when x + y = a and xy = b.",
          "Compare surds by raising them to a common power: for 2^(1/2) and 3^(1/3), raise both to the 6th power and compare 8 with 9.",
        ],
      },
      {
        title: "Logarithms",
        items: [
          "log_a x = y means aʸ = x, with a > 0, a ≠ 1 and x > 0.",
          "log(xy) = log x + log y; log(x/y) = log x − log y; log(xⁿ) = n log x.",
          "log_a b × log_b c = log_a c, and log_a b = 1/log_b a. Also a^(log_a x) = x.",
          "log₁₀ 2 ≈ 0.301 and log₁₀ 3 ≈ 0.477. A number N has floor(log₁₀ N) + 1 digits.",
          "Domain: the argument must be positive and the base positive and not 1. Check every solution against this.",
          "Change of base, and powers in the base or argument:",
        ],
        tex: [String.raw`\log_a b = \frac{\log b}{\log a}`, String.raw`\log_{a^m} b^{n} = \frac{n}{m}\log_a b`],
      },
    ],
    thought: [
      "Indices: write every number in prime bases, then equate the exponents.",
      "Surds: rationalise, or look for a perfect-square pattern.",
      "Logs: bring everything to one base and turn sums of logs into the log of a product.",
      "Solve, then reject any answer that breaks the domain.",
    ],
    patterns: [
      "Exponential equations solved by matching bases.",
      "Simplifying powers through prime factorisation.",
      "Comparing surds or powers.",
      "Telescoping surd sums and nested roots.",
      "Evaluating log expressions with the product, quotient and power rules.",
      "Log equations, with invalid roots rejected.",
      "Change-of-base chains.",
      "Counting digits with log 2 and log 3.",
      "Log equations that become quadratics with t = log x.",
    ],
    examples: [
      { q: "Solve 2^(x + 3) = 32.", a: "32 = 2⁵, so x + 3 = 5. Answer: x = 2." },
      { q: "Solve 9ˣ = 27^(x − 1).", a: "3^(2x) = 3^(3x − 3), so 2x = 3x − 3. Answer: x = 3." },
      { q: "Simplify 81^(3/4) × 32^(−2/5).", a: "81^(3/4) = 3³ = 27 and 32^(−2/5) = 2⁻² = 1/4. Answer: 27/4." },
      { q: "Which is largest: 2^(1/2), 3^(1/3) or 6^(1/6)?", a: "Raise all three to the 6th power: 8, 9 and 6. Answer: 3^(1/3)." },
      { q: "Evaluate 1/(√1 + √2) + 1/(√2 + √3) + … + 1/(√80 + √81).", a: "Rationalising, each term is √(n + 1) − √n, so the sum telescopes to √81 − √1. Answer: 8." },
      { q: "Simplify √(7 + 2√10).", a: "Find two numbers that add to 7 and multiply to 10: 5 and 2. Answer: √5 + √2." },
      { q: "Evaluate log₂ 8 + log₃ 81 − log₅ 125.", a: "3 + 4 − 3. Answer: 4." },
      { q: "Solve log₂ x + log₂ (x − 2) = 3.", a: "x(x − 2) = 2³ = 8, so x² − 2x − 8 = 0 and x = 4 or −2. Reject −2, which makes both arguments negative. Answer: x = 4." },
      { q: "Evaluate log₂ 3 × log₃ 4 × log₄ 5 × … × log₆₃ 64.", a: "The chain collapses to log₂ 64. Answer: 6." },
      { q: "How many digits does 2⁵⁰ have? (log 2 = 0.301)", a: "50 × 0.301 = 15.05, so 2⁵⁰ lies between 10¹⁵ and 10¹⁶. Answer: 16." },
      { q: "Solve log_x 4 + log₄ x = 5/2.", a: "Let t = log₄ x, so log_x 4 = 1/t. Then t + 1/t = 5/2, giving 2t² − 5t + 2 = 0 and t = 2 or 1/2. Answer: x = 16 or x = 2." },
    ],
    traps: [
      "log(a + b) is not log a + log b.",
      "Keeping roots that make a log’s argument zero or negative.",
      "(aᵐ)ⁿ is a^(mn), but a^(mⁿ) is different: (2³)² = 2⁶ while 2^(3²) = 2⁹.",
    ],
    practice: [
      { q: "Solve 5^(2x − 1) = 125.", a: "x = 2: 125 = 5³, so 2x − 1 = 3." },
      { q: "Simplify 16^(3/4) + 27^(2/3).", a: "17: 8 + 9." },
      { q: "Which is larger, 3^(1/3) or 4^(1/4)?", a: "3^(1/3): raise both to the 12th power and compare 81 with 64." },
      { q: "Evaluate log₂ (1/32) + log₉ 27.", a: "−3.5: log₂ (1/32) = −5 and log₉ 27 = 3/2." },
      { q: "Solve log₃ (x + 1) + log₃ (x − 1) = 1.", a: "x = 2: x² − 1 = 3, and x = −2 makes the arguments negative." },
      { q: "Given log 2 = 0.301, how many digits does 8²⁰ have?", a: "19: 8²⁰ = 2⁶⁰, and 60 × 0.301 = 18.06." },
    ],
  },
  {
    n: 15,
    slug: "progressions",
    title: "Progressions (AP & GP)",
    short: "Progressions",
    group: "Algebra",
    lede: "Progression questions are mostly formula substitution: the nth term and sum of an AP, the sum and infinite sum of a GP. CAT dresses them up as savings plans, rows of seats, bouncing balls and “how many numbers between A and B”.",
    asked:
      "Terms or sums at two positions are given and you find others; you count or sum the numbers in a range with a divisibility property; you find the common terms of two APs; infinite GP sums (bouncing balls); word problems with steady increases; Sₙ given as a formula in n.",
    concepts: [
      {
        items: [
          "AP: a, a + d, a + 2d, … with nth term Tₙ = a + (n − 1)d.",
          "AP sum = n × (first + last)/2, and the average of an AP = (first + last)/2.",
          "Three terms in an AP: write them as a − d, a, a + d (they sum to 3a).",
          "Number of terms from p to q with gap d = (q − p)/d + 1.",
          "GP: a, ar, ar², … with Tₙ = arⁿ⁻¹ and Sₙ = a(rⁿ − 1)/(r − 1).",
          "The common terms of two APs form an AP whose gap is the LCM of the two gaps.",
          "If Sₙ = An² + Bn, the series is an AP with d = 2A and first term A + B; any term is Tₙ = Sₙ − Sₙ₋₁.",
          "1 + 2 + … + n = n(n + 1)/2; the sum of the first n squares is n(n + 1)(2n + 1)/6; of the first n cubes, [n(n + 1)/2]²; of the first n odd numbers, n².",
          "The AP sum and the infinite GP sum:",
        ],
        tex: [String.raw`S_n = \frac{n}{2}\left[2a + (n-1)d\right]`, String.raw`S_\infty = \frac{a}{1-r}\quad (|r| < 1)`],
      },
    ],
    thought: [
      "Decide AP (constant difference) or GP (constant ratio).",
      "Write a and d (or r). Two given facts give two equations.",
      "For counting in a range, find the first and last valid terms, then count.",
      "For bouncing balls, count the first drop once and every rebound height twice (up and down).",
    ],
    patterns: [
      "Two terms given: find d and a, then any term or sum.",
      "Counting or summing numbers in a range divisible by k.",
      "Common terms of two APs.",
      "Infinite GP: bouncing balls, repeating decimals.",
      "Steady increases in word problems: savings, rows of seats.",
      "Sₙ given as a formula in n.",
      "Average of AP terms (overlaps with Section 9).",
    ],
    examples: [
      { q: "Find the sum of all two-digit multiples of 3.", a: "They run from 12 to 99: (99 − 12)/3 + 1 = 30 terms. Sum = 30 × (12 + 99)/2. Answer: 1,665." },
      { q: "The 5th term of an AP is 19 and the 12th is 47. Find the sum of the first 20 terms.", a: "7d = 28, so d = 4 and a = 19 − 16 = 3. S₂₀ = 10 × (2 × 3 + 19 × 4) = 10 × 82. Answer: 820." },
      { q: "How many terms are common to 4, 9, 14, …, 199 and 3, 10, 17, …, 220?", a: "The first common term is 24 (in the second list: 3, 10, 17, 24). Common terms step by LCM(5, 7) = 35: 24, 59, 94, 129, 164, 199. The next, 234, passes 199. Answer: 6." },
      { q: "A ball dropped from 20 m rebounds to 3/4 of its previous height every time. What total distance does it travel before stopping?", a: "20 down, then each rebound height up and down: 20 + 2 × [15/(1 − 3/4)] = 20 + 2 × 60. Answer: 140 m." },
      { q: "Riya saves ₹500 in the first month and ₹100 more each month after that. After how many months will her total savings reach ₹11,000?", a: "Sₙ = n/2 × [1,000 + 100(n − 1)] = 50n² + 450n = 11,000, so n² + 9n − 220 = 0 = (n + 20)(n − 11). Check: 11 × (500 + 1,500)/2 = 11,000. Answer: 11 months." },
      { q: "The sum of the first n terms of an AP is 3n² + 5n. Find the 10th term.", a: "T₁₀ = S₁₀ − S₉ = 350 − 288. Check with d = 6 and a = 8: 8 + 9 × 6 = 62. Answer: 62." },
    ],
    traps: [
      "Off-by-one errors when counting terms: it is (last − first)/d + 1.",
      "Using the infinite GP formula when |r| ≥ 1.",
      "Counting a bouncing ball’s first drop twice, or its rebounds once.",
    ],
    practice: [
      { q: "How many three-digit numbers are divisible by 7?", a: "128: from 105 (7 × 15) to 994 (7 × 142)." },
      { q: "The 3rd term of an AP is 11 and the 7th is 27. Find the 15th term.", a: "59: d = 4 and a = 3." },
      { q: "Find the sum of the infinite GP 12 + 6 + 3 + …", a: "24: 12 ÷ (1 − 1/2)." },
      { q: "Three numbers in an AP add to 24 and multiply to 440. Find them.", a: "5, 8 and 11: the middle term is 24/3 = 8, and 8(64 − d²) = 440 gives d = 3." },
      { q: "A theatre has 20 seats in the first row and 2 more in each row behind. How many seats are there in 15 rows?", a: "510: the last row has 48 seats, and 15 × (20 + 48)/2 = 510." },
      { q: "Find the sum of the first 20 odd numbers.", a: "400: the first n odd numbers add to n²." },
    ],
  },
  {
    n: 16,
    slug: "inequalities-modulus",
    title: "Inequalities, Modulus & Max-Min",
    short: "Inequalities",
    group: "Algebra",
    lede: "Treat this chapter as number-line thinking: a modulus is a distance, a quadratic inequality is “between or outside the roots”, and AM ≥ GM answers most max-min questions. In the exam, take only the direct versions; the harder ones are a time sink.",
    asked:
      "Count the integer solutions of a linear or quadratic inequality; solve a modulus equation; minimise a sum of distances; find the minimum of x + k/x or the maximum product for a fixed sum; an inequality inside a word problem.",
    concepts: [
      {
        items: [
          "Multiplying or dividing an inequality by a negative number flips its direction.",
          "|x| = x if x ≥ 0 and −x if x < 0. |x − a| is the distance between x and a on the number line.",
          "|x − a| < b means a − b < x < a + b. |x − a| > b means x < a − b or x > a + b.",
          "With a < b: (x − a)(x − b) < 0 means a < x < b, and (x − a)(x − b) > 0 means x < a or x > b.",
          "|x − a| + |x − b| is smallest, equal to |a − b|, for any x between a and b. For three points a < b < c, |x − a| + |x − b| + |x − c| is smallest at the middle point x = b.",
          "For positive numbers, a fixed sum gives the largest product when the parts are equal, and a fixed product gives the smallest sum when they are equal. So x + 1/x ≥ 2 for x > 0.",
          "The AM–GM inequality behind those rules:",
        ],
        tex: [String.raw`\frac{a+b}{2} \ge \sqrt{ab} \qquad (a, b > 0;\ \text{equality when } a = b)`],
      },
    ],
    thought: [
      "Move everything to one side and factorise.",
      "Mark the critical points (roots, and where each modulus is zero) on a number line.",
      "Test one value in each region, or use the “between or outside” rule.",
      "When counting, list the integers in the final range and watch strict (<) against non-strict (≤) signs.",
      "For max/min with positive terms, look for a fixed sum or product and apply AM–GM.",
    ],
    patterns: [
      "Counting integer solutions of linear or quadratic inequalities.",
      "Modulus equations, by cases or by distance.",
      "Modulus inequalities turned into ranges.",
      "Minimum of a sum of distances.",
      "AM–GM: the minimum of ax + b/x, or the maximum product for a fixed sum.",
      "Inequalities inside word problems, such as the point where one plan becomes cheaper.",
    ],
    examples: [
      { q: "How many integers satisfy x² − 7x + 10 < 0?", a: "(x − 2)(x − 5) < 0 means 2 < x < 5, so x = 3 or 4. Answer: 2." },
      { q: "How many integers satisfy |2x − 5| ≤ 7?", a: "−7 ≤ 2x − 5 ≤ 7, so −2 ≤ 2x ≤ 12 and −1 ≤ x ≤ 6. Answer: 8." },
      { q: "Solve |x − 3| + |x + 2| = 7.", a: "The points −2 and 3 are 5 apart, so any x between them gives a sum of 5. Moving t beyond either end adds 2t, so 5 + 2t = 7 and t = 1. Check: |1| + |6| = 7 and |−6| + |−1| = 7. Answer: x = 4 or x = −3." },
      { q: "Find the minimum of |x − 1| + |x − 4| + |x − 10|.", a: "Take the middle point x = 4: 3 + 0 + 6. Answer: 9." },
      { q: "Find the minimum of 4x + 9/x for x > 0.", a: "The product 4x × 9/x = 36 is fixed, so the sum is smallest when 4x = 9/x = 6, at x = 1.5. Answer: 12." },
      { q: "Two positive integers add to 21. What is their largest possible product?", a: "Make them as equal as possible: 10 and 11. Answer: 110." },
      { tag: "word problem", q: "One phone plan costs ₹200 a month plus ₹0.50 a minute; another costs a flat ₹500. Above how many minutes is the flat plan cheaper?", a: "200 + 0.5m > 500 gives m > 600. Answer: above 600 minutes." },
    ],
    traps: [
      "Forgetting to flip the sign when multiplying by a negative.",
      "Mixing up strict and non-strict endpoints when counting integers.",
      "Applying AM–GM to terms that can be negative.",
    ],
    practice: [
      { q: "How many integers x satisfy −3 < 2x + 1 ≤ 9?", a: "6: −2 < x ≤ 4." },
      { q: "Solve |x − 4| = 2x + 1.", a: "x = 1: the case x ≥ 4 gives x = −5, which contradicts it; check |−3| = 3 = 2 + 1." },
      { q: "How many integers satisfy x² − 9x + 14 ≤ 0?", a: "6: 2 ≤ x ≤ 7." },
      { q: "Find the minimum of x + 16/x for x > 0.", a: "8, at x = 4." },
      { q: "A rectangle has a perimeter of 40 m. What is its largest possible area?", a: "100 m²: a 10 m square." },
      { q: "Find the minimum value of |x − 2| + |x − 9|.", a: "7: the distance from 2 to 9." },
    ],
  },
];

export const chapterBySlug = (slug: string) => chapters.find((c) => c.slug === slug);
